import { createHash } from "node:crypto";

export const GUESS_PLAYER_QUESTION_COUNT = 5;
export const GUESS_PLAYER_TIME_LIMIT_SECONDS = 7;

export type Footballer = {
  id: string;
  name: string;
  aliases: string[];
  country: string;
  club: string;
  position: string;
};

export const footballers: Footballer[] = [
  {
    id: "esp-unai-simon",
    name: "Unai Simón",
    aliases: [],
    country: "España",
    club: "Athletic Bilbao",
    position: "Arquero",
  },
  {
    id: "esp-david-raya",
    name: "David Raya",
    aliases: [],
    country: "España",
    club: "Arsenal",
    position: "Arquero",
  },
  {
    id: "esp-joan-garcia",
    name: "Joan García",
    aliases: [],
    country: "España",
    club: "Espanyol",
    position: "Arquero",
  },
  {
    id: "esp-pedro-porro",
    name: "Pedro Porro",
    aliases: [],
    country: "España",
    club: "Tottenham Hotspur",
    position: "Defensor",
  },
  {
    id: "esp-marcos-llorente",
    name: "Marcos Llorente",
    aliases: [],
    country: "España",
    club: "Atlético de Madrid",
    position: "Defensor",
  },
  {
    id: "esp-aymeric-laporte",
    name: "Aymeric Laporte",
    aliases: [],
    country: "España",
    club: "Al-Nassr",
    position: "Defensor",
  },
  {
    id: "esp-pau-cubarsi",
    name: "Pau Cubarsí",
    aliases: [],
    country: "España",
    club: "Barcelona",
    position: "Defensor",
  },
  {
    id: "esp-marc-pubill",
    name: "Marc Pubill",
    aliases: [],
    country: "España",
    club: "Almería",
    position: "Defensor",
  },
  {
    id: "esp-eric-garcia",
    name: "Eric García",
    aliases: [],
    country: "España",
    club: "Barcelona",
    position: "Defensor",
  },
  {
    id: "esp-marc-cucurella",
    name: "Marc Cucurella",
    aliases: [],
    country: "España",
    club: "Chelsea",
    position: "Defensor",
  },
  {
    id: "esp-alejandro-grimaldo",
    name: "Alejandro Grimaldo",
    aliases: [],
    country: "España",
    club: "Bayer Leverkusen",
    position: "Defensor",
  },
  {
    id: "esp-rodrigo-hernandez",
    name: "Rodrigo Hernández",
    aliases: ["rodri", "rodrigo", "rodrigo hernandez"],
    country: "España",
    club: "Manchester City",
    position: "Mediocampista",
  },
  {
    id: "esp-martin-zubimendi",
    name: "Martín Zubimendi",
    aliases: [],
    country: "España",
    club: "Real Sociedad",
    position: "Mediocampista",
  },
  {
    id: "esp-pedri-gonzalez",
    name: "Pedri González",
    aliases: ["pedri"],
    country: "España",
    club: "Barcelona",
    position: "Mediocampista",
  },
  {
    id: "esp-fabian-ruiz",
    name: "Fabián Ruiz",
    aliases: [],
    country: "España",
    club: "Paris Saint-Germain",
    position: "Mediocampista",
  },
  {
    id: "esp-mikel-merino",
    name: "Mikel Merino",
    aliases: [],
    country: "España",
    club: "Arsenal",
    position: "Mediocampista",
  },
  {
    id: "esp-pablo-paez-gavi",
    name: "Pablo Páez Gavi",
    aliases: ["gavi", "pablo gavi"],
    country: "España",
    club: "Barcelona",
    position: "Mediocampista",
  },
  {
    id: "esp-alex-baena",
    name: "Álex Baena",
    aliases: [],
    country: "España",
    club: "Villarreal",
    position: "Mediocampista",
  },
  {
    id: "esp-mikel-oyarzabal",
    name: "Mikel Oyarzabal",
    aliases: [],
    country: "España",
    club: "Real Sociedad",
    position: "Delantero",
  },
  {
    id: "esp-lamine-yamal",
    name: "Lamine Yamal",
    aliases: [],
    country: "España",
    club: "Barcelona",
    position: "Delantero",
  },
  {
    id: "esp-ferran-torres",
    name: "Ferran Torres",
    aliases: [],
    country: "España",
    club: "Barcelona",
    position: "Delantero",
  },
  {
    id: "esp-borja-iglesias",
    name: "Borja Iglesias",
    aliases: [],
    country: "España",
    club: "Celta de Vigo",
    position: "Delantero",
  },
  {
    id: "esp-dani-olmo",
    name: "Dani Olmo",
    aliases: [],
    country: "España",
    club: "Barcelona",
    position: "Delantero",
  },
  {
    id: "esp-victor-munoz",
    name: "Víctor Muñoz",
    aliases: [],
    country: "España",
    club: "Real Madrid Castilla",
    position: "Delantero",
  },
  {
    id: "esp-nico-williams",
    name: "Nico Williams",
    aliases: [],
    country: "España",
    club: "Athletic Bilbao",
    position: "Delantero",
  },
  {
    id: "esp-yeremy-pino",
    name: "Yeremy Pino",
    aliases: [],
    country: "España",
    club: "Villarreal",
    position: "Delantero",
  },
  {
    id: "fra-mike-maignan",
    name: "Mike Maignan",
    aliases: [],
    country: "Francia",
    club: "AC Milan",
    position: "Arquero",
  },
  {
    id: "fra-william-saliba",
    name: "William Saliba",
    aliases: [],
    country: "Francia",
    club: "Arsenal",
    position: "Defensor",
  },
  {
    id: "fra-dayot-upamecano",
    name: "Dayot Upamecano",
    aliases: [],
    country: "Francia",
    club: "Bayern Múnich",
    position: "Defensor",
  },
  {
    id: "fra-ibrahima-konate",
    name: "Ibrahima Konaté",
    aliases: [],
    country: "Francia",
    club: "Liverpool",
    position: "Defensor",
  },
  {
    id: "fra-jules-kounde",
    name: "Jules Koundé",
    aliases: [],
    country: "Francia",
    club: "Barcelona",
    position: "Defensor",
  },
  {
    id: "fra-theo-hernandez",
    name: "Theo Hernández",
    aliases: [],
    country: "Francia",
    club: "AC Milan",
    position: "Defensor",
  },
  {
    id: "fra-aurelien-tchouameni",
    name: "Aurélien Tchouaméni",
    aliases: [],
    country: "Francia",
    club: "Real Madrid",
    position: "Mediocampista",
  },
  {
    id: "fra-adrien-rabiot",
    name: "Adrien Rabiot",
    aliases: [],
    country: "Francia",
    club: "Olympique de Marsella",
    position: "Mediocampista",
  },
  {
    id: "fra-ngolo-kante",
    name: "N'Golo Kanté",
    aliases: ["ngolo kante", "kante"],
    country: "Francia",
    club: "Al-Ittihad",
    position: "Mediocampista",
  },
  {
    id: "fra-kylian-mbappe",
    name: "Kylian Mbappé",
    aliases: ["mbappe", "kylian mbappe"],
    country: "Francia",
    club: "Real Madrid",
    position: "Delantero",
  },
  {
    id: "fra-ousmane-dembele",
    name: "Ousmane Dembélé",
    aliases: [],
    country: "Francia",
    club: "Paris Saint-Germain",
    position: "Delantero",
  },
  {
    id: "fra-michael-olise",
    name: "Michael Olise",
    aliases: [],
    country: "Francia",
    club: "Bayern Múnich",
    position: "Delantero",
  },
  {
    id: "fra-rayan-cherki",
    name: "Rayan Cherki",
    aliases: [],
    country: "Francia",
    club: "Olympique de Lyon",
    position: "Delantero",
  },
  {
    id: "fra-desire-doue",
    name: "Désiré Doué",
    aliases: [],
    country: "Francia",
    club: "Paris Saint-Germain",
    position: "Delantero",
  },
  {
    id: "fra-bradley-barcola",
    name: "Bradley Barcola",
    aliases: [],
    country: "Francia",
    club: "Paris Saint-Germain",
    position: "Delantero",
  },
  {
    id: "fra-maghnes-akliouche",
    name: "Maghnes Akliouche",
    aliases: [],
    country: "Francia",
    club: "Mónaco",
    position: "Delantero",
  },
  {
    id: "fra-jean-philippe-mateta",
    name: "Jean-Philippe Mateta",
    aliases: [],
    country: "Francia",
    club: "Crystal Palace",
    position: "Delantero",
  },
  {
    id: "fra-marcus-thuram",
    name: "Marcus Thuram",
    aliases: [],
    country: "Francia",
    club: "Inter de Milán",
    position: "Delantero",
  },
  {
    id: "arg-emiliano-martinez",
    name: "Emiliano Martínez",
    aliases: ["dibu", "dibu martinez", "emiliano martinez"],
    country: "Argentina",
    club: "Aston Villa",
    position: "Arquero",
  },
  {
    id: "arg-geronimo-rulli",
    name: "Gerónimo Rulli",
    aliases: [],
    country: "Argentina",
    club: "Olympique de Marsella",
    position: "Arquero",
  },
  {
    id: "arg-juan-musso",
    name: "Juan Musso",
    aliases: [],
    country: "Argentina",
    club: "Atlético de Madrid",
    position: "Arquero",
  },
  {
    id: "arg-cristian-romero",
    name: "Cristian Romero",
    aliases: ["cuti romero", "cristian romero"],
    country: "Argentina",
    club: "Tottenham Hotspur",
    position: "Defensor",
  },
  {
    id: "arg-lisandro-martinez",
    name: "Lisandro Martínez",
    aliases: [],
    country: "Argentina",
    club: "Manchester United",
    position: "Defensor",
  },
  {
    id: "arg-leonardo-balerdi",
    name: "Leonardo Balerdi",
    aliases: [],
    country: "Argentina",
    club: "Olympique de Marsella",
    position: "Defensor",
  },
  {
    id: "arg-nahuel-molina",
    name: "Nahuel Molina",
    aliases: [],
    country: "Argentina",
    club: "Atlético de Madrid",
    position: "Defensor",
  },
  {
    id: "arg-nicolas-tagliafico",
    name: "Nicolás Tagliafico",
    aliases: [],
    country: "Argentina",
    club: "Olympique de Lyon",
    position: "Defensor",
  },
  {
    id: "arg-rodrigo-de-paul",
    name: "Rodrigo De Paul",
    aliases: [],
    country: "Argentina",
    club: "Atlético de Madrid",
    position: "Mediocampista",
  },
  {
    id: "arg-alexis-mac-allister",
    name: "Alexis Mac Allister",
    aliases: [],
    country: "Argentina",
    club: "Liverpool",
    position: "Mediocampista",
  },
  {
    id: "arg-enzo-fernandez",
    name: "Enzo Fernández",
    aliases: [],
    country: "Argentina",
    club: "Chelsea",
    position: "Mediocampista",
  },
  {
    id: "arg-leandro-paredes",
    name: "Leandro Paredes",
    aliases: [],
    country: "Argentina",
    club: "Roma",
    position: "Mediocampista",
  },
  {
    id: "arg-giovani-lo-celso",
    name: "Giovani Lo Celso",
    aliases: [],
    country: "Argentina",
    club: "Real Betis",
    position: "Mediocampista",
  },
  {
    id: "arg-exequiel-palacios",
    name: "Exequiel Palacios",
    aliases: [],
    country: "Argentina",
    club: "Bayer Leverkusen",
    position: "Mediocampista",
  },
  {
    id: "arg-valentin-barco",
    name: "Valentín Barco",
    aliases: [],
    country: "Argentina",
    club: "Sevilla",
    position: "Mediocampista",
  },
  {
    id: "arg-lionel-messi",
    name: "Lionel Messi",
    aliases: ["messi", "leo messi", "lionel messi"],
    country: "Argentina",
    club: "Inter Miami",
    position: "Delantero",
  },
  {
    id: "arg-julian-alvarez",
    name: "Julián Álvarez",
    aliases: [],
    country: "Argentina",
    club: "Atlético de Madrid",
    position: "Delantero",
  },
  {
    id: "arg-lautaro-martinez",
    name: "Lautaro Martínez",
    aliases: [],
    country: "Argentina",
    club: "Inter de Milán",
    position: "Delantero",
  },
  {
    id: "arg-thiago-almada",
    name: "Thiago Almada",
    aliases: [],
    country: "Argentina",
    club: "Botafogo",
    position: "Delantero",
  },
  {
    id: "arg-nico-paz",
    name: "Nico Paz",
    aliases: [],
    country: "Argentina",
    club: "Como",
    position: "Delantero",
  },
  {
    id: "arg-nicolas-gonzalez",
    name: "Nicolás González",
    aliases: [],
    country: "Argentina",
    club: "Juventus",
    position: "Mediocampista",
  },
  {
    id: "arg-giuliano-simeone",
    name: "Giuliano Simeone",
    aliases: [],
    country: "Argentina",
    club: "Atlético de Madrid",
    position: "Delantero",
  },
  {
    id: "arg-jose-manuel-lopez",
    name: "José Manuel López",
    aliases: [],
    country: "Argentina",
    club: "Palmeiras",
    position: "Delantero",
  },
  {
    id: "eng-jordan-pickford",
    name: "Jordan Pickford",
    aliases: [],
    country: "Inglaterra",
    club: "Everton",
    position: "Arquero",
  },
  {
    id: "eng-dean-henderson",
    name: "Dean Henderson",
    aliases: [],
    country: "Inglaterra",
    club: "Crystal Palace",
    position: "Arquero",
  },
  {
    id: "eng-james-trafford",
    name: "James Trafford",
    aliases: [],
    country: "Inglaterra",
    club: "Burnley",
    position: "Arquero",
  },
  {
    id: "eng-john-stones",
    name: "John Stones",
    aliases: [],
    country: "Inglaterra",
    club: "Manchester City",
    position: "Defensor",
  },
  {
    id: "eng-marc-guehi",
    name: "Marc Guéhi",
    aliases: [],
    country: "Inglaterra",
    club: "Crystal Palace",
    position: "Defensor",
  },
  {
    id: "eng-ezri-konsa",
    name: "Ezri Konsa",
    aliases: [],
    country: "Inglaterra",
    club: "Aston Villa",
    position: "Defensor",
  },
  {
    id: "eng-reece-james",
    name: "Reece James",
    aliases: [],
    country: "Inglaterra",
    club: "Chelsea",
    position: "Defensor",
  },
  {
    id: "eng-tino-livramento",
    name: "Tino Livramento",
    aliases: [],
    country: "Inglaterra",
    club: "Newcastle United",
    position: "Defensor",
  },
  {
    id: "eng-dan-burn",
    name: "Dan Burn",
    aliases: [],
    country: "Inglaterra",
    club: "Newcastle United",
    position: "Defensor",
  },
  {
    id: "eng-jarell-quansah",
    name: "Jarell Quansah",
    aliases: [],
    country: "Inglaterra",
    club: "Liverpool",
    position: "Defensor",
  },
  {
    id: "eng-djed-spence",
    name: "Djed Spence",
    aliases: [],
    country: "Inglaterra",
    club: "Tottenham Hotspur",
    position: "Defensor",
  },
  {
    id: "eng-declan-rice",
    name: "Declan Rice",
    aliases: [],
    country: "Inglaterra",
    club: "Arsenal",
    position: "Mediocampista",
  },
  {
    id: "eng-jude-bellingham",
    name: "Jude Bellingham",
    aliases: [],
    country: "Inglaterra",
    club: "Real Madrid",
    position: "Mediocampista",
  },
  {
    id: "eng-kobbie-mainoo",
    name: "Kobbie Mainoo",
    aliases: [],
    country: "Inglaterra",
    club: "Manchester United",
    position: "Mediocampista",
  },
  {
    id: "eng-nico-oreilly",
    name: "Nico O'Reilly",
    aliases: [],
    country: "Inglaterra",
    club: "Manchester City",
    position: "Defensor/Mediocampista",
  },
  {
    id: "eng-harry-kane",
    name: "Harry Kane",
    aliases: [],
    country: "Inglaterra",
    club: "Bayern Múnich",
    position: "Delantero",
  },
  {
    id: "eng-bukayo-saka",
    name: "Bukayo Saka",
    aliases: [],
    country: "Inglaterra",
    club: "Arsenal",
    position: "Delantero",
  },
  {
    id: "eng-phil-foden",
    name: "Phil Foden",
    aliases: [],
    country: "Inglaterra",
    club: "Manchester City",
    position: "Mediocampista",
  },
  {
    id: "eng-eberechi-eze",
    name: "Eberechi Eze",
    aliases: [],
    country: "Inglaterra",
    club: "Crystal Palace",
    position: "Delantero",
  },
  {
    id: "eng-anthony-gordon",
    name: "Anthony Gordon",
    aliases: [],
    country: "Inglaterra",
    club: "Newcastle United",
    position: "Delantero",
  },
  {
    id: "eng-ollie-watkins",
    name: "Ollie Watkins",
    aliases: [],
    country: "Inglaterra",
    club: "Aston Villa",
    position: "Delantero",
  },
  {
    id: "eng-ivan-toney",
    name: "Ivan Toney",
    aliases: [],
    country: "Inglaterra",
    club: "Al-Ahli",
    position: "Delantero",
  },
];

const footballersById = new Map(footballers.map((footballer) => [footballer.id, footballer]));

export function getFootballerById(id: string): Footballer | null {
  return footballersById.get(id) ?? null;
}

export function normalizeAnswer(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/['’`´]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function normalizedAcceptedAnswers(footballer: Footballer) {
  return new Set([footballer.name, ...footballer.aliases].map(normalizeAnswer).filter(Boolean));
}

export function isCorrectFootballerAnswer(footballer: Footballer, answer: string): boolean {
  const normalized = normalizeAnswer(answer);
  if (!normalized) return false;
  return normalizedAcceptedAnswers(footballer).has(normalized);
}

export function findFootballerByAnswer(answer: string): Footballer | null {
  const normalized = normalizeAnswer(answer);
  if (!normalized) return null;
  const matches = footballers.filter((footballer) =>
    normalizedAcceptedAnswers(footballer).has(normalized),
  );
  return matches.length === 1 ? matches[0] : null;
}

function scoreForSeed(seed: string, footballer: Footballer): number {
  const hash = createHash("sha256").update(`${seed}:${footballer.id}`).digest();
  return hash.readUInt32BE(0);
}

export function selectGuessPlayerQuestions(seed: string, sessionId = ""): Footballer[] {
  return [...footballers]
    .sort(
      (a, b) => scoreForSeed(`${seed}:${sessionId}`, a) - scoreForSeed(`${seed}:${sessionId}`, b),
    )
    .slice(0, GUESS_PLAYER_QUESTION_COUNT);
}
